DEVICE_PORT = "/dev/ttyUSB0"
BAUD_RATE   = 57600
PROTOCOL    = 2.0
SERVO_ID    = 1

ADDR_TORQUE_ENABLE        = 64
ADDR_OPERATING_MODE       = 11
ADDR_GOAL_POSITION        = 116
ADDR_PRESENT_POSITION     = 132
ADDR_PRESENT_VELOCITY     = 128
ADDR_PRESENT_CURRENT      = 126
ADDR_PRESENT_TEMPERATURE  = 146
ADDR_PROFILE_VELOCITY     = 112
ADDR_PROFILE_ACCELERATION = 108

MODE_POSITION = 3

ENCODER_RESOLUTION = 4096
CENTER_RAW         = 2048   # 0° użytkownika = środek zakresu serwa
